name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build_project:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests

  run_tests:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with Maven
        run: mvn test 