name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build_project:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests

  run_tests:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests with Maven
        run: mvn test

  package_application:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Package with Maven
        run: mvn package

  security_analysis:
    name: Security Analysis
    runs-on: ubuntu-latest
    needs: package_application
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy_simulation:
    runs-on: ubuntu-latest
    needs: security_analysis
    steps:
      - name: Simulate Deploy
        run: echo "Deploy realizado com sucesso" 