name: Lint and Test Workflow

on:
  workflow_call:
    inputs:
      run_tests:
        description: 'Execute test job'
        required: false
        type: boolean
        default: true
      run_lint:
        description: 'Execute lint job'
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Execute test job'
        required: true
        type: boolean
        default: true
      run_lint:
        description: 'Execute lint job'
        required: true
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

  lint:
    needs: setup
    if: inputs.run_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Check code style
        run: mvn checkstyle:check

  test:
    needs: lint
    if: inputs.run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests
        run: mvn test 